### ISSUE TITLE
riva can't handle multiple sentences

### ISSUE THREAD

**Issue by kfatehi** [kfatehi/riva_tts_proxy#1]
the readaloud project makes effort to clean up input, but riva can't handle this input without throwing an error, why?

![image](https://user-images.githubusercontent.com/175305/235315379-412595bb-47b5-4279-8a2d-b953e2168456.png)

**Comment by kfatehi** [comment]
here's another bad input

```
{'language_code': 'en-US', 'encoding': 1, 'sample_rate_hz': 48000, 'voice_name': 'English-US.Female-1', 'text': '<speak><prosody pitch="-0.1499999999999999" rate="100%">On the eve of May 1st, the International Labor Day, a number of trade union and labor activists have been arrested in Iran. Labor activists in Iran say that agents raided the house of imprisoned teacher Mohammad Habibi on Friday night during the meeting of civil and trade union activists with the family. An official has also confirmed that among the seasonal workers on strike in South Pars, four thousand people have lost their jobs. The protest organizing council of contract oil workers has invited people to strike and gather on May 1.\n\n</prosody></speak>'}
[2023-04-29 19:02:03,420] ERROR in app: Exception on /tts [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app.py", line 55, in tts
    resp = riva_tts.synthesize(**req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/riva/client/tts.py", line 68, in synthesize
    return func(req, metadata=self.auth.get_auth_metadata())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/grpc/_channel.py", line 1030, in __call__
    return _end_unary_response_blocking(state, call, False, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/grpc/_channel.py", line 910, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Error: Triton model failed during inference. Error message: in ensemble 'fastpitch_hifigan_ensemble-English-US', FAILURE"
        debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2023-04-29T19:02:03.420165563+00:00", grpc_status:2, grpc_message:"Error: Triton model failed during inference. Error message: in ensemble \'fastpitch_hifigan_ensemble-English-US\', FAILURE"}"
>
```

**Comment by kfatehi** [comment]
the answer is in the riva container log. basically it doesn't like sentences.

E0429 19:38:13.568981 102 tts-preprocessor.cc:96] preprocessor had an errorSSML Input does not currently support split on sentence. Input text too long.<speak><prosody pitch="0.15000000000000036" rate="100%">The text-to-speech TTS pipeline implemented for the Riva TTS service is based on a two-stage pipeline. Riva first generates a mel-spectrogram using the first model, and then generates speech using the second model. This pipeline forms a TTS system that enables you to synthesize natural sounding speech from raw transcripts without any additional information such as patterns or rhythms of speech.

</prosody></speak>

**Comment by kfatehi** [comment]
solved by tokenizing sentences using nltk
